apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-service
spec:
  selector:
    app: kubernetes-demo
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
